services:
  - name: telegram-bot
    type: web  # This runs as a web service
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_TOKEN
        value: ""
